@startuml
group verify client id
	IdpSrv -> IdpDB : findBy(//<client id>//)

		IdpDB --> IdpSrv : //<value>//
		note right
			{
				"clientId": "//<client id>//",
				"channel": "//<client channel>//",
				"clientSecret": "//<client secret>//",
				"description": "//<description>//"
			}
		end note

	note over IdpSrv #Orange
		if nothing is found, return HTTP 401 (unauthorized)
		if an error is returned from db, return HTTP 500 (server error)
		if "channel" != ATM, return HTTP 401 (unauthorized)
		if "//<secret hash>//" is not correct, return HTTP 401 (unauthorized)
	end note
end
@enduml