@startuml
group interaction with nodo
	NoticeSrv -> Nodo : POST /closepayment
		note left
			!include_many ../nodo_request/close_payment_ok.frag
		end note


	alt ok

		Nodo --> NoticeSrv : HTTP 200 (ok)
			note right
				!include_many ../nodo_response/ko_for_close_payment.frag
			end note

	else bad request

		Nodo --> NoticeSrv : HTTP 400 (bad request)

	else not found

		Nodo --> NoticeSrv : HTTP 404 (not found)

	end alt
end
@enduml