@startuml
group interaction with nodo
	NoticeSrv -> Nodo : POST /closepayment
		note left
			!include_many ../nodo_request/close_payment_ko.frag
		end note


	Nodo --> NoticeSrv : don't care
end
@enduml