@startuml
group find preset
	PresetSrv -> PresetDB : find(//<query>//)
		note left
			__query__
			{
				"paTaxCode": "//<pa tax code>//",
				"subscriberId": "//<subscriber id>//",
				"presetId": "//<preset id>//"
			}
		end note
	
	
	PresetDB --> PresetSrv : //<value>//
		note right
			!include_many get_preset_to_execute.frag
		end note
end
@enduml