@startuml
group find presets
	PresetSrv -> PresetDB : find(//<query>//)
		note left
			__query__
			{
				"paTaxCode": "//<pa tax code>//"
			}
		end note
	
	
	PresetDB --> PresetSrv : //<value>//
		note right
			!include_many get_presets.frag
		end note
end
@enduml