@startuml
group create access token proper
	IdpSrv -> IdpSrv : generate //<access token payload>//
		note left
			{
				"iat": "//<current timestamp>//",
				"exp": "//<current timestamp + <access token duration>>//",
				"scope": "//<grant #1>// //<grant #2>// ... //<grant #n>//",
				"acquirerId": "//<acquirer id>//",
				"channel": "POS",
				"merchantId": "//<merchant id>//",
				"clientId": "//<client id>//",
				"terminalId": "//<terminal id>//" 
			}
		end note


	IdpSrv -> IdpSrv : generate //<access token header>//
		note left
			{
				"alg": "RS256",
				"kid": "//<kid of selected <key pair>>//"
			}
		end note


	IdpSrv -> IdpSrv : sign access token by means of the selected //<key pair>//


	IdpSrv -> IdpSrv : <access token> = base64UrlEncode(//<access token header>//) + "." + base64UrlEncode(//<access token payload>//) + "." + base64UrlEncode(//<access token signature>//)
end
@enduml