@startuml
group create access token
	!include_many ../common/get_valid_key_pair.puml


	!include_many create_access_token_proper.puml


	opt //<required scope>// = offline_access
		!include_many create_refresh_token.puml
	end
end
@enduml