@startuml
group interaction with nodo
	NoticeSrv -> Nodo : POST /activatePaymentNotice
		note left
			!include_many ../nodo_request/activate.frag
		end note


	Nodo --> NoticeSrv : HTTP 200 (ok)
		note right
			!include_many ../nodo_response/activate_ok.frag
		end note
end
@enduml