@startuml
!include_many ../../common/skin.puml

participant "Portal Back-end" as Portal
participant MIL

Portal ->  MIL    : add terminal (access token + gt id + terminal id + company code + slave terminal id)
MIL    ->  MIL    : store terminal data
MIL    --> Portal : ok

@enduml