@startuml
!include_many ../../common/skin.puml

== Verify ==
POS  ->  MIL  : verify
MIL  ->  Nodo : verifyPaymentNoticeReq
Nodo --> MIL
MIL  --> POS

== Activate ==
POS  ->  MIL  : activate
MIL  ->  Nodo : activatePaymentNoticeReqV2
Nodo --> MIL
MIL  --> POS

== Retrieve Fees ==
POS ->  MIL : get fee
MIL ->  GEC : GetFeesByPsp
GEC --> MIL
MIL --> POS

== Pre-close ==
POS ->  MIL : pre-close
MIL --> POS

== e-Money Transaction ==
POS <-> PSP : e-Money Transaction

== Close ==
POS  ->  MIL  : close
MIL  ->  Nodo : closePaymentReqV2
Nodo --> MIL
MIL  --> POS

== Polling #1 (eg) ==
POS  ->  MIL : get status
MIL  --> POS

== Notify ==
Nodo ->  PSP  : pspNotifyPaymentReqV2
PSP  --> Nodo

== Payment Outcome ==
PSP  ->  Nodo : sendPaymentOutcomeV2
Nodo --> PSP

== Polling #2 (eg) ==
POS ->  MIL : get status
MIL --> PSP

== Payment Result ==
Nodo ->  MIL : sendPaymentResultReq
MIL  --> Nodo

== Polling #3 (eg) ==
POS ->  MIL : get status
MIL --> POS

@enduml