@startuml
group#Gold 1st polling cycle
	{wait_for_attempt_1_end} Client -> NoticeSrv : GET /payments///<transaction id>//
		note left
			!include_many ../request/polling.frag
		end note


	{wait_for_attempt_1_begin} <-> {wait_for_attempt_1_end} : <font color="darkorange">1) Retry-After: //<retry after>//</font>


	!include_many ../stored_trx_data/read_trx_with_close_ok_with_resp_ok.puml


	{wait_for_attempt_2_begin} NoticeSrv --> Client : HTTP 200 (ok)
		note right
			!include_many ../stored_trx_data/close_ok_with_resp_ok.frag
		end note
end
@enduml