@startuml
!include_many ../../common/skin.puml
!include_many ../../common/actors.puml

group#Gold close
	Client -> NoticeSrv : PATCH /payments///<transaction id>//
		note left
			!include_many ../request/close_ok.frag
		end note
	
	
	!$client = NoticeSrv
	!include_many ../common/get_acquirer_conf.frag
	
	
	!include_many ../nodo_interaction/close_payment_ok_with_resp_ok.puml
	
	
	NoticeSrv -> NoticeDB : persist(//<value>//)
		note left
			!include_many ../stored_trx_data/close_ok_with_resp_ok.frag
		end note
	
	
	NoticeDB --> NoticeSrv : don't care
	
	
	{wait_for_attempt_1_begin} NoticeSrv --> Client : HTTP 200 (ok)
		note right
			!include_many ../response/close_ok_with_resp_ok.frag
		end note
end
@enduml