@startuml
group#Gold //<max retries>//-th polling cycle
	{wait_for_attempt_2_end} Client -> NoticeSrv : GET /payments///<transaction id>//
		note left
			!include_many ../request/polling.frag
		end note


	{wait_for_attempt_2_begin} <-> {wait_for_attempt_2_end} : <font color="darkorange">//<max retries>//) Retry-After: //<retry after>//</font>


	!include_many ../stored_trx_data/read_trx_with_close_ok_with_resp_ok.puml


	NoticeSrv --> Client : HTTP 200 (ok)
		note right
			!include_many ../stored_trx_data/close_ok_with_resp_ok.frag
		end note
end
@enduml