@startuml
!include_many ../../common/skin.puml
!include_many ../../common/actors.puml

!include_many close_ok_with_resp_ok.puml
!include_many 1st_polling_cycle_with_pending_status.puml
!include_many callback_ok.puml
!include_many 2nd_polling_cycle_with_closed_status.puml
@enduml