@startuml
!include_many ../../common/skin.puml
!include_many ../../common/actors.puml

group#Gold close
	Client -> NoticeSrv : PATCH /payments///<transaction id>//
		note left
			!include_many ../request/close_ok.frag
		end note


	NoticeSrv -> NoticeDB : findByIdOptional(//<transaction id>//)


	NoticeDB --> NoticeSrv : <value>
		note right
			!include_many ../stored_trx_data/pre_close.frag
		end note
		
		note over NoticeSrv #Orange
			in case of document not
			found, return HTTP 404
		end note


	!$client = NoticeSrv
	!include_many ../common/get_acquirer_conf.frag


	!include_many ../nodo_interaction/close_payment_ok_with_resp_ko.puml


	NoticeSrv -> NoticeDB : persist(//<value>//)
		note left
			!include_many ../stored_trx_data/close_ok_with_resp_ko.frag
		end note


	NoticeDB --> NoticeSrv : ack
		note left #Orange
			in case of error, retry
		end note


	!include_many ../preset_interaction/trx_with_close_ok_with_resp_ko.puml


	NoticeSrv --> Client : HTTP 200 (ok)
		note left
			!include_many ../response/ko_for_close_ok.frag
		end note

		note across #Red
			<font color="white">**retry and if the issuer persists the e-money transaction must be rolled back or the user must be charged back**</font>
		end note
end
@enduml