group build tokens payload
	mil_auth -> mil_auth : generate //<access token payload>//
		note right
			__//<access token payload>//__
			{
				"sub": "//<terminal uuid>//",
				"aud": "mil.pagopa.it",
				"iss": "https:////<host name>///mil-auth",
				"iat": //<current unix epoch>//,
				"exp": //<current unix epoch>// + //<access token duration>//,
				"payeeCode": "//<payeeCode>//",
				"channel": "POS",
				"terminalHandlerId": "//<terminal handler id>//",
				"terminalId": "//<terminal id>//",
				"groups": [
					"SlavePos", <font color="red"><&arrow-left> //Present if <slave> is **true**.//</font>
					"NoticePayer", <font color="red"><&arrow-left> //Present if <pagopa> is **true**.//</font>
					"PayWithIDPay" <font color="red"><&arrow-left> //Present if <idpay> is **true**.//</font>
				],
				"pagoPaConf": { <font color="red"><&arrow-left> //Present if <pagopa> is **true**.//</font>
					"pspId": "//<psp id>//",
					"brokerId": "//<broker id>//",
					"channelId": "//<channel id>//"
				}
			}
		end note

	mil_auth -> mil_auth : generate //<refresh token payload>//
		note right
			__//<refresh token payload>//__
			{
				"jti": "//<refresh token id>//",
				"sub": "//<terminal uuid>//",
				"iat": //<current unix epoch>//,
				"exp": //<current unix epoch>// + //<refresh token duration>//
				"channel": "POS",
				"scope": "offline_access"
			}
		end note
end