group verify client id 
	!include_many get_azure_access_token_for_storage.puml

	group get client id file
		mil_auth -> azure_st ++ : GET //<storage account base url>///clients///<client id>//.json
			note left
				__header__
				x-ms-version: 2019-07-07
				Authorization: Bearer //<access token for storage account>//
			end note

		azure_st --> mil_auth -- : HTTP 200 (ok)
			note right
				__body__
				{
					"id": "<client id>",
					"channel": "POS",
					"grantTypes": [
						"device_code",
						"refresh_token"
					]
				}
			end note

		note over mil_auth #Orange
			On //<client id>// file not found, return HTTP 401 (unauthorized) with specific error body.
			On any other failure, return HTTP 500 (server error) with specific error body. 
		end note
	end

	mil_auth -> mil_auth : verify channel and grant types

	note over mil_auth #Orange
		On channel or grant type mismatch, return HTTP 401 (unauthorized) with specific error body.
	end note
end