participant "Client" as Client

participant "Company Portal" as Portal

participant "POS" as Pos

box Multichannel Integration Layer #GhostWhite
    participant "Other Service" as Other
    
    participant "Auth Service" as IdpSrv
    database "Cache" as IdpCache
    database "DB" as IdpDB
	
	participant "Payment Notice Service" as NoticeSrv
	database "DB" as NoticeDB
	
	participant "Preset Operation" as PresetSrv
	database "DB" as PresetDB
	
	participant "IDPay Service" as IDPaySrv
	database "DB" as IDPayDB
	
	participant "Azure AD" as AzureAD
	participant "Azure Key Vault" as AzureKV
	participant "Azure Storage Account" as AzureST
end box

participant "Nodo" as Nodo
participant "IDPay" as IDPay
participant "Poynt Services" as Poynt
participant "IPZS" as IPZS