@startuml
!include_many ../common/skin.puml
!include_many ../common/actors.puml

group Protect PAN
	Client -> PANTokenizer : POST /tokens
		rnote left
			__header__
			- Version: //<api version>//
			__request body__
			{
				"pan": "//<pan>//"
			}
		end note
	        
	
	PANTokenizer --> Client : HTTP 200 (ok) or 201 (created)
		rnote left
			__response body__
			{
				"panToken": "//<pan token>//"
			}
		end note
end
@enduml