@startuml
hide empty description

state CREATED          #Gray;text:White
state PRE_CLOSE        #Orange
state ERROR_ON_PAYMENT #Green;text:White
state CLOSED           #Green;text:White
state ERROR_ON_CLOSE   #Red;text:White
state ABORTED          #Gray;text:White

[*]              --> CREATED          : 1
CREATED          --> ABORTED          : 2
CREATED          --> PRE_CLOSE        : 3
PRE_CLOSE        --> ERROR_ON_PAYMENT : 4
PRE_CLOSE        --> ERROR_ON_CLOSE   : 5
PRE_CLOSE        --> CLOSED           : 6
ERROR_ON_PAYMENT --> [*] 
CLOSED           --> [*]
ERROR_ON_CLOSE   --> [*]
ABORTED          --> [*]

@enduml
