@startuml
hide empty description

[*]                      --> PRE_CLOSING : 1
PRE_CLOSING              --> KO_CLOSING : 2
KO_CLOSING               --> KO_CLOSED_UNSUCCESSFULLY : 3
KO_CLOSING               --> KO_CLOSED_SUCCESSFULLY : 4
KO_CLOSED_UNSUCCESSFULLY --> [*]
KO_CLOSED_SUCCESSFULLY   --> [*]

PRE_CLOSING              --> OK_CLOSING : 5
OK_CLOSING               --> OK_CLOSED_UNSUCCESSFULLY : 6
OK_CLOSING               --> OK_OUTCOME : 10
OK_CLOSING               --> OUTCOME_PENDING : 7
OK_CLOSED_UNSUCCESSFULLY --> [*]

OUTCOME_PENDING          --> OK_OUTCOME : 8
OUTCOME_PENDING          --> KO_OUTCOME : 9
OK_CLOSING               --> KO_OUTCOME : 11
OK_OUTCOME               --> [*]
KO_OUTCOME               --> [*]

PRE_CLOSING              --> OK_OUTCOME : 12
PRE_CLOSING              --> KO_OUTCOME : 13

@enduml
