@startuml
group interaction with idpay
	IDPaySrv -> IDPay : POST /idpay/payment/qr-code/merchant
		note left
			!include_many ../idpay_request/create_trx.frag
		end note


	Nodo --> NoticeSrv : HTTP 200 (ok)
		note right
			!include_many ../nodo_response/activate_ko.frag
		end note
end
@enduml