@startuml
group read trx data from db
	NoticeSrv -> NoticeDB : find(//<query>//)
		note left
			__query__
			{
				"acquirerId": "//<acquirer id>//",
				"channel": "//<channel>//",
				"merchantId": "//<merchant id>//",
				"terminalId": "//<terminal id>//",
				"insertTimestamp": {
					$gt: "<current date - 31 days formatted in yyyy-MM-dd>T23:59:59.999Z"
				}
			}
		end note
	
	
	NoticeDB --> NoticeSrv : //<value>//
		note right
			!include trx_list.frag
		end note
end
@enduml