@startuml
group read trx data from db
	NoticeSrv -> NoticeDB : find(//<transaction id>//)


	NoticeDB --> NoticeSrv : //<value>//
		note right
			!include_many ../stored_trx_data/callback_ko.frag
		end note
end
@enduml