@startuml
group write trx data to db
	NoticeSrv -> NoticeDB : save(//<value>//)
		note left
			!include_many ../stored_trx_data/callback_ok.frag
		end note


	NoticeDB --> NoticeSrv : ack
		note over NoticeSrv #Orange
			in case of error, retry
		end note
	end group
@enduml