@startuml 

participant "EC" as ec
participant "NodoSPC" as pagopa 
participant "MIL-FE" as mil_fe #99FF99
participant "MIL" as mil #99FF99

participant "GPD" as gpd
participant "Checkout" as checkout 



ec -> pagopa : nodoInviaCarrelloRTP
pagopa -> pagopa : redirectMod1Messages
pagopa -> mil : fwd_nodoInviaCarrelloRPT
mil -> mil : createNewRequest (milRequest)
mil --> pagopa : milRequestUrl

pagopa --> ec : 200 - (wispUrl=milRequestUrl)

Create mil_fe
ec -> mil_fe : redirectTo milRequestUrl(milRequestID)


par MIL Creates PDs 
    hnote over mil : MilRequestIdStatus = PENDIND
    loop "#RPT"
    mil -> gpd : new PD
    gpd --> mil : 200 OK 
    end  

    mil -> checkout : postCards()
    checkout --> mil : 302 checkoutUrl
    mil -> mil : updateStatus(checkOutUrl) 
    hnote over mil : MilRequestIdStatus = READY

 else "Mil-FE waiting READY"
 loop 
  mil_fe -> mil : GET milRequestID
  alt PENDING
  mil --> mil_fe : Status=PENDING
  else READY
  mil --> mil_fe : Status=READY (CheckoutUrl is not empty ) 
  mil_fe -> checkout : redirectTo CheckOutUrl 
  end
  end 
end

== PAYMENT on CHECKOUT ==
... 
==END OF PAYMENT ==
pagopa -> gpd : sendReceipt
loop 
mil -> gpd : getReceipt
gpd --> mil : receipt 
end 

note over mil : Se la receipt non esiste dopo 30min \n si deve creare una RT-
mil -> pagopa : fwd_NodoInviaRT
pagopa -> pagopa : forwardMod1Messages
pagopa -> ec : nodoInviaRT
ec --> pagopa : ok
pagopa --> mil  : ok 










@enduml 