@startuml
!include_many ../common/skin.puml
!include_many ../common/actors.puml


group#Gold accept
	Client -> TCSrv : POST /acceptedTermsConds
		rnote left
			__header__
			- Version: //<api version>//
			- AcquirerId: //<acquirer id>//
			- Channel: //<channel>//
			- TerminalId: //<terminal id>//
			- SessionId: //<session id>//
		end note
		
	!$client = TCSrv
	!include_many ../session/check__tc_not_accepted.puml
	
	!include_many ../common/protect_tax_code.puml
	
	TCSrv -> TCDB : upsertItem ( //<tax code token>//, { "version": , "//<t&c version>//" } )
	
	TCDB --> TCSrv
	
	!include_many ../save-new-cards/check.puml
	
	group Update session
		TCSrv -> SessionSrv : PATCH /sessions///<session id>//
			rnote left
				__header__
				- Version: //<api version>//
				- AcquirerId: //<acquirer id>//
				- Channel: //<channel>//
				- TerminalId: //<terminal id>//
			
				__request body__
				{
					"termsAndCondsAccepted": true,
					"saveNewCards": //<save new cards flag>//
				}
			end note
	
		SessionSrv --> TCSrv : HTTP 202 (accepted)
	
		SessionSrv -> SessionCache : JSON.SET //<session id>// $.termsAndCondsAccepted 'true'
	
		SessionCache --> SessionSrv
		
		SessionSrv -> SessionCache : JSON.SET //<session id>// $.saveNewCards '//<save new cards flag>//'
	
		SessionCache --> SessionSrv
	end
	
	
	
	TCSrv --> Client : HTTP 201 (created)
		rnote left
			__response body__
			{
				"saveNewCards": //<save new cards flag>//
			}
		end note
end
@enduml