group Check acceptance of T&C
	SessionSrv -> TCSrv : GET /acceptedTermsConds///<tax code token>//
		rnote left
			__header__
			- Version: //<api version>//
			- AcquirerId: //<acquirer id>//
			- Channel: //<channel>//
			- TerminalId: //<terminal id>//
		end note
		
	!include_many ../common/protect_tax_code.puml
	
	TCSrv -> TCDB : readItem ( //<tax code token>// )
	
	TCDB --> TCSrv : { "version": "//<t&c version>//" }
	
	TCSrv -> TCSrv : check //<t&c version>//
	
	TCSrv --> SessionSrv : HTTP 200 (ok)
		rnote left
			__response body__
			{
				"outcome": "OK"
			}
		end note
end
