participant "POS" as pos
actor "Operator" as operator
participant "Management\nPortal" as management
participant "mil-payment-notice" as mil
participant "mil-auth" as mil_auth
participant "mil-terminal-registry" as mil_registry
participant "pagoPA" as pagopa
database "pagopa-trx\n(MongoDB)" as registry