@startuml
note left
	__header__
	RequestId: //<request id>//
	Authorization: Bearer //<access token>//
	__body__
	{
		"gtId": "//<gt id>//",
		"terminalId": "//<terminal id>//",
		"payeeCode": "//<payee tax code>//",
		"nodo": {
			"pspId": "//<psp id>//",
			"brokerId": "//<brokerId>//",
			"channelId": "//<channel id>//"
		}
	}
end note
@enduml