group Interaction with the Nodo
	NoticeSrv -> Nodo : POST /closepayment
		rnote left
			__request body__
			{
				"paymentTokens": [
					"//<payment token>//",
					.
					.
					.
				],
				"outcome": "OK",
				"idPSP": "//<psp id>//",
				"idBrokerPSP": "//<psp broker id>//",
				"idChannel": "//<channel id>//",
				"paymentMethod": "//<payment method>//",
				"transactionId": "//<transaction id>//",
				"totalAmount": "//<total amount>//",
				"fee": "//<total fee>//",
				"timestampOperation": "//<operation timestamp>//",
				"additionalPaymentInformations": { }
			}
		end note
				
	opt 200
		Nodo --> NoticeSrv : HTTP 200 (ok)
			rnote left
				__response body__
				{
					"outcome": "OK"
				}
			end note
	else 200
		Nodo --> NoticeSrv : HTTP 200 (ok)
			rnote left
				//Unparsable/unknown response//
			end note
	else Timeout
		Nodo -[#red]-> NoticeSrv : //timeout//
	else 408 
		Nodo --> NoticeSrv : HTTP 408 (request timeout)
	else not in (200, 400, 404, 408, 422) 
		Nodo --> NoticeSrv : HTTP //status code// not in (200, 400, 404, 408, 422)
	end
end
