@startuml
!include_many ../common/skin.puml

== Verify ==
loop for each payment notice
	!include_many verify.puml
end

== Activate ==
loop for each payment notice 
	!include_many activate.puml
end

== Retrieve Fees ==
!include_many get_fee.puml

== e-Money Transaction ==
SWClient <-> TerminalHandler : e-Money Transaction

== Confirm ==
!include_many confirm.puml

@enduml