@startuml
!include_many ../../common/skin.puml
!include_many ../../common/actors.puml

group#Gold pre-close
	Client -> NoticeSrv : POST /payments
		note left
			!include_many ../request/pre_close.frag
		end note
		
		
		loop for each //<payment token>//
			NoticeSrv -> NoticeCache: get(//<payment token>//)
			NoticeCache --> NoticeSrv: //<value>//
			note right
				!include_many ../common/stored_notice_data.frag
			end note
		end loop
		
		
		NoticeSrv -> NoticeDB : persist(//<value>//)
			note left
				!include_many ../stored_trx_data/pre_close.frag
			end note
		
		
		alt db ok
		
			NoticeDB --> NoticeSrv : ok
			
			NoticeSrv --> Client : HTTP 201 (created)
				note right
					!include_many ../response/pre_close.frag
				end note
		
		else duplicate key
		
			NoticeDB --> NoticeSrv : duplicate key
			
			NoticeSrv --> Client : HTTP 409 (conflict)
		
		else db ko
		
			NoticeDB --> NoticeSrv : ko
			
			NoticeSrv --> Client : HTTP 500 (server error)
				note left #Orange
					retry
				end note
		
		end alt
end
@enduml