group Retrieve //<save new cards flag>// - <font color="red">If this fails the processing continues as //<save new cards flag>// is false</font>
	$client -> Wallet : GET /enabledServices///<tax code>///saveNewCards
	    rnote left
    		__header__
    		- Version: //<api version>//
    	end note
	Wallet --> $client : HTTP 200 (ok)
		rnote left
			__response body__
			{
				"saveNewCards": //<save new cards flag>//
			}
		end note
end
