@startuml
!include_many ../common/skin.puml
!include_many ../common/actors.puml

group pre-save
	Client -> WalletWrp : POST /cards
		rnote left
			__header__
			- Version: //<api version>//
			- AcquirerId: //<acquirer id>//
			- Channel: //<channel>//
			- TerminalId: //<terminal id>//
			- SessionId: //<session id>//
			__request body__
			{
				"panToken": "//<pan token>//"
			}
		end note
	
	!$client = WalletWrp
	!include_many ../session/check__session_not_found.puml
	
	WalletWrp --> Client : HTTP 400 (bad request)
		rnote left
			__response body__
			{
			    "violations": [
			        {
			            "message": "SESessionSrvION_NOT_FOUND"
			        }
			    ]
			}
		end note
end
@enduml