@startuml
!include_many ../common/skin.puml
!include_many ../common/actors.puml

group pre-save
	Client -> WalletWrp : POST /cards
		rnote left
			__header__
			- Version: //<api version>//
			- AcquirerId: //<acquirer id>//
			- Channel: //<channel>//
			- TerminalId: //<terminal id>//
			- SessionId: //<session id>//
			__request body__
			{
				"panToken": "//<pan token>//"
			}
		end note
	
	!$client = WalletWrp
	!include_many ../session/check.puml
	
	WalletWrp -> Wallet : POST /cards
		rnote left
			__header__
			- Version: //<api version>//
			
			__request body__
			{
				"panToken": "//<pan token>//",
				"taxCode": "//<tax code>//"
			}
		end note
	
	Wallet --> WalletWrp : HTTP __not__ 201
	
	WalletWrp --> Client : HTTP 500 (server error)
end
@enduml