@startuml
!include_many ../common/skin.puml
!include_many ../common/actors.puml

group#Gold get transaction
	Client -> IDPaySrv : GET /transactions///<mil transaction id>//
		note left
			!include_many request/get_transaction.frag
		end note
	
	group read trx data from db
		IDPaySrv -> IDPayDB  : find(//<mil transaction id>//)
		return //<result>// 
	end
	
	alt //<result>// is found
		note over IDPayDB
			!include_many stored_trx_data/on_get__retrieve.frag
		end note
		
		IDPaySrv -> IDPay : GET /idpay/mil/payment///<idpay transaction id>///status
			note left
				!include_many idpay_request/get_transaction.frag
			end note
		
		alt transaction found
			IDPay --> IDPaySrv : HTTP 200 (found)
				note right
					!include_many idpay_response/get_transaction.frag
				end note
			
			opt //<by cie>// = true && //<idpay status>// = IDENTIFIED
				IDPaySrv -> IDPay : PUT /idpay/mil/payment/idpay-code///<idpay transaction id>///preview
					note left
						!include_many idpay_request/get_second_factor.frag
					end note
				
				IDPay --> IDPaySrv : HTTP 200 (ok)
					note right
						!include_many idpay_response/get_second_factor.frag
					end note	
					
				note over IDPaySrv #Orange
					if this interaction with IDPay went wrong, return HTTP 500 (server error) with error body
				end note
			end

			group write trx data to db
				IDPaySrv -> IDPayDB : update(//<value>//)
					note left
						!include_many stored_trx_data/on_get__update.frag
					end note
				
				return //don't care//
			end
			
			IDPaySrv --> Client : HTTP 200 (found)
				note right
					!include_many response/get_transaction.frag
				end note
		else other
			IDPay --> IDPaySrv : //any error (http status codes != 200, unparsable response, unexpeted response, ...)//
			IDPaySrv --> Client : HTTP 500 (server error)
				note right
					!include_many response/error.frag
				end note
		end
	else //<result>// is not found
		IDPaySrv --> Client : HTTP 404 (not found)
			note right
				!include_many response/error.frag
			end note
	else //<result>// is error
		IDPaySrv --> Client : HTTP 500 (server error)
			note right
				!include_many response/error.frag
			end note
	end
end
@enduml