@startuml

group retrieve azure access token
	IDPaySrv -> AzureAD : GET ${IDENTITY_ENDPOINT}?resource=https://vault.azure.net&api-version=2019-08-01
		note left
			!include_many azuread_request/get_access_token.frag
		end note
	
	AzureAD --> IDPaySrv : HTTP 200 (ok)
		note right
			!include_many azuread_response/get_access_token.frag
		end note
end

@enduml