@startuml
!include_many ../../common/skin.puml
!include_many ../../common/actors.puml

group#Gold enquiry
	Client -> NoticeSrv : GET /payments
		note left
			!include_many ../request/enquiry.frag
		end note


	!include_many ../stored_trx_data/read_trx_list.puml


	NoticeSrv --> Client : HTTP 200 (ok)
		note right
			!include_many ../stored_trx_data/trx_list.frag
		end note
end
@enduml