@startuml
group find grants
	IdpSrv -> IdpDB : find(//<query>//)
		note left
			__query__
			{
				"acquirerId": "//<acquirerId>//",
				"channel": "POS",
				"merchantId": "//<merchant id>//",
				"clientId": "//<client id>//",
				"terminalId": "//<terminal id>//"
			}
		end note
		
	IdpDB --> IdpSrv : //<value>//
		note right
			__value__
			{
				"acquirerId": "//<acquirerId>//",
				"channel": "POS",
				"merchantId": "//<merchant id>//",
				"clientId": "//<client id>//",
				"terminalId": "//<terminal id>//",
				"grants": [
					"//<grant #1>//",
					"//<grant #2>//",
					.
					.
					.
					"//<grant #n>//"
				]
			}
		end note


	opt nothing is found
		IdpSrv -> IdpDB : find(//<query>//)
			note left
				__query__
				{
					"acquirerId": "//<acquirerId>//",
					"channel": "POS",
					"merchantId": "//<merchant id>//",
					"clientId": "//<client id>//",
					"terminalId": "NA"
				}
			end note

		IdpDB --> IdpSrv : //<value>//
			note right
				__value__
				{
					"acquirerId": "//<acquirerId>//",
					"channel": "POS",
					"merchantId": "//<merchant id>//",
					"clientId": "//<client id>//",
					"terminalId": "NA",
					"grants": [
						"//<grant #1>//",
						"//<grant #2>//",
						.
						.
						.
						"//<grant #n>//"
					]
				}
			end note
	end
end
@enduml