@startuml

box POS #GhostWhite
	participant "PagoPA App" as pago
	participant "CB2 App" as cb2
end box

box NEXI #GhostWhite
	participant "GT" as gt
	participant "Identity Provider" as idp
end box

box PagoPA #GhostWhite
	participant "API Manager" as apim
	participant "Multi-channel Integration Layer" as mil
end box

== Init ==
pago -> cb2 : init

cb2 -> gt : 18xx 
	rnote left
		Il messaggio 18xx è cifrato con Kser
		e contiene il //<tid>// del terminale
	end note

gt -> gt : check POS
	rnote left
		Il GT esegue i controlli standard che
		esegue su tutti i msg ricevuti dal POS
	end note

gt -> idp : get jwt (in: //<tid>//)

idp --> gt : //<jwt>//

gt --> cb2 : //<jwt>//

cb2 --> pago : //<jwt>//, //<tid>//, //<acquirer id>//, //<merchant id>// 


== Access Token Usage ==
pago -> apim : Generic request
	rnote left
		__header__
		- Authorization: //<jwt>//
		- Version: //<api version>//
		- AcquirerId: //<acquirer id>//
		- Channel: //<channel>//
		- TerminalId: //<tid>//
	end note

apim -> apim : check //<jwt>//.//<tid>// == header.TerminalId

apim -> apim : check //<jwt>//.//<iat>//

apim -> idp : get /.well-known/jwks.json
idp --> apim : jwks.json

apim -> apim : select by kid

apim -> apim : check signature

apim -> mil : Generic request
mil --> apim : Generic response

apim --> pago : Generic response

@enduml
