@startuml

!pragma teoz true
skinparam style strictuml
skinparam maxMessageSize 300
skinparam sequenceMessageAlign left
skinparam sequenceArrowColor #blue
autonumber "<font color='red'><b><u>##</u></b></font>"


actor "User" as USR

box "POS"
	participant "PagoPA App" as APP
	participant "Poynt Service" as SRV
end box

box "Poynt"
	participant "Poynt API\nservices.poynt.net" as PNT
end box

box "PagoPA"
	participant "Multi-channel\nIntegration Layer" as MIL
	participant "Database" as DBS
	participant "Key Vault" as KVL
end box


USR ->  APP: Start

opt Terminal Certificate expired or POS rebooted
	hnote over SRV, PNT: Getting //<poynt access token>//

	APP ->  SRV : Get Poynt access token
	SRV --> APP : //<poynt access token>//
	
	APP ->  APP : Generate RSA key pair
	APP ->  APP : Generate CSR with DN = "CN=//<terminal id>//, OU=//<merchant id>//, O=//<acquirer id>//"
	APP ->  APP : Store //<private key>//
	
	APP ->  MIL : POST /enrollments
		note left
			__header__
			- RequestId: //<request id>//
			- Version: //<api version>//
			- AcquirerId: //<acquirer id>//
			- Channel: POS
			- MerchantId: //<merchant id>//
			- TerminalId: //<terminal id>//
			
			__body__
			{
				"accessToken": "//<poynt access token>//,
				"businessId": "//<business id>//",
				"csr": "//<csr>//"
			}
		end note
	
	MIL ->  PNT : GET /businesses///<business id>//
		note right
			__header__
			Api-Version: 1.2
			Authorization: Bearer //<poynt access token>//
			Content-Type: application/json
			POYNT-REQUEST-ID: //don't care//
		end note

	PNT --> MIL : HTTP 200 (ok)
		note left
			__body__
			//<business object>//
		end note
	
	MIL ->  MIL : Check coherence between //<business object>// and other data received from the POS
	
	MIL ->  DBS : Store //<business object>//
	DBS --> MIL : Ok
	MIL ->  KVL : Get CA private key
	KVL --> MIL : //<ca private key>//
	MIL ->  MIL : Generate //<client certificate>//
	
	MIL ->  DBS : Store
		note left
			{
				"acquirerId": "//<acquirer id>//",
				"merchantId": "//<merchant id>//",
				"terminalId": "//<terminal id>//",
				"certificateSn": "//<client certificate s/n>//"
			}
		end note
	
	DBS --> MIL : Ok
	
	MIL --> APP : HTTP 201 (created)
		note right
			__body__
			{
				"certificate": "//<client certificate>//"
			}
		end note
	
	APP ->  APP : Store //<client certificate>//
end opt

APP --> USR


USR ->  APP : Interation
APP ->  APP : Build //<request body>//
group <font color="red">https with mutual-auth managed by APP GW by means of CA certificate</font>
	APP ->  MIL : Request
	note left
			__header__
			- RequestId: //<request id>//
			- Version: //<api version>//
			- AcquirerId: //<acquirer id>//
			- Channel: POS
			- MerchantId: //<merchant id>//
			- TerminalId: //<terminal id>//
			
			__body__
			//<request body>//
		end note
	
	MIL ->  MIL : Verify coherence between client certifcate DN and other http headers
	MIL ->  DBS : Get client certificate s/n
	DBS --> MIL : //<client certificate s/n>//
	MIL ->  MIL : Verify coherence between stored client certificate s/n and the one contained in the received certificate
	
	note over MIL
		Execute business logic
	end note

	MIL --> APP : Response 
end

APP --> USR

@enduml