actor "Operator" as operator
actor "POS Installer" as installer
actor "mil other service" as other

participant "Management\nPortal" as management
participant "POS" as pos

participant "mil-terminal-registry" as mil_registry

database "terminal-registry\n(MongoDB)" as registry