group get azure access token
	mil_auth -> azure_ad ++ : GET //${IDENTITY_ENDPOINT}//?api-version=2019-08-01\n&resource=https://vault.azure.net
		note left
			__header__
			x-identity-header: //${IDENTITY_HEADER}//
		end note

	azure_ad --> mil_auth -- : HTTP 200 (ok) 
		note right
			__body__
			{
				"token_type": "Bearer",
				"expires_on": //don't care//,
				"client_id": "//don't care//",
				"resource": "//don't care//"
				"access_token": "//<access token for key vault>//"
			}
		end note

	note over mil_auth #Orange
		On any failure, return HTTP 500 (server error) with specific error body. 
	end note
end

