group #E0FFF0 get keys
	mil -> azure_kv ++ : GET //<key vault base url>///keys?api-version=7.4
		note left
			__header__
			Authorization: Bearer //<access token for key vault>//
		end note

	azure_kv --> mil -- : HTTP 200 (ok)
		note right
			__body__
			{
				"value": [
					{
						"kid": "//<key vault base url>///keys///<key name>//",
						"attributes": {
							"enabled": //<enabled>//,
							"nbf": //<not before>//,
							"exp": //<expiration>//,
							"created": //<issued at>//
						}
					},
					.
					.
					.
				]
			}
		end note

    note over mil #Orange
		On any failure, return HTTP 500 (server error) with specific error body. 
	end note
end