group #CCFFFF get azure access token
	mil -> azure_ad ++ : GET //${IDENTITY_ENDPOINT}//?api-version=2019-08-01\n&resource=https://storage.azure.com
		note left
			__header__
			x-identity-header: //${IDENTITY_HEADER}//
		end note

	azure_ad --> mil -- : HTTP 200 (ok) 
		note right
			__body__
			{
				"token_type": "Bearer",
				"expires_on": //don't care//,
				"client_id": "//don't care//",
				"resource": "//don't care//"
				"access_token": "//<access token for storage account>//"
			}
		end note

    note over mil #Orange
		On any failure, return HTTP 500 (server error) with specific error body. 
	end note
end