group get terminal data by id
	mil_registry -> registry ++ : findAll(//query document//)
		note left
			__//query document//__
			{
				"terminalUuid": "//<terminal uuid>//",
				"payeeCode": "//<payee code>//"
			}
		end note

	registry --> mil_registry -- : //document//
		note right
			__//document//__
			{
				"terminalUuid": "//<terminal uuid>//",
				"serviceProviderId": "//<service provider id>//",
				"terminalHandlerId": "//<terminal handler id>//",
				"terminalId": "//<terminal id>//",
				"enabled": //<enabled>//,
				"payeeCode": "//<payee code>//",
				"slave": "//<slave>//",
				"workstations": [
					//<array of workstations>//
				]
				"pagoPa": "//<pagopa>//",
				"pagoPaConf": {
					"pspId": "//<psp id>//",
					"brokerId": "//<broker id>//",
					"channelId": "//<channel id>//"
				},
				"idpay": "//<idpay>//"
			}
		end note
	
    note over mil_registry #Orange
	    On terminal not found, return HTTP 404 (not found) with specific error body.
	    On any other failure, return HTTP 500 (server error) with specific error body. 
    end note
end