group #7FE5CE get terminal data by id
	mil -> registry ++ : findById(//<terminal uuid>//)

	registry --> mil -- : //document//
		note right
			__//document//__
			{
				"uuid": "//<terminal uuid>//",
				"manId": "//<client id of the subject who registered the POS>//",
				"gtId": "//<gt id>//",
				"terminalId": "//<terminal id>//",
				"enabled": //<enabled>//,
				"payeeCode": "//<payee code>//",
				"slave": "//<slave>//",
				"pagoPa": "//<pagopa>//",
				"pspId": "//<psp id>//",
				"brokerId": "//<broker id>//",
				"channelId": "//<channel id>//",
				"idpay": "//<idpay>//"
			}
		end note
	
    note over mil #Orange
	    On terminal not found, return HTTP 404 (not found) with specific error body.
	    On any other failure, return HTTP 500 (server error) with specific error body. 
    end note
end