group get terminals data
	mil_registry -> registry ++ : findAll(//query document//).page(//<page number>//, //<page size>//).list()
		note left
			__//query document//__
			{
				"payeeCode": "//<payee code>//"
			}
		end note

	registry --> mil_registry -- : //page//
		note right
			__//page//__
			[
				{
					"terminalUuid": "//<terminal uuid>//",
					"serviceProviderId": "//<service provider id>//",
					"terminalHandlerId": "//<terminal handler id>//",
					"terminalId": "//<terminal id>//",
					"enabled": //<enabled>//,
					"payeeCode": "//<payee code>//",
					"slave": "//<slave>//",
					"workstations": [
						//<array of workstations>//
					],
					"pagoPa": "//<pagopa>//",
					"pagoPaConf": {
						"pspId": "//<psp id>//",
						"brokerId": "//<broker id>//",
						"channelId": "//<channel id>//"
					},
					"idpay": "//<idpay>//"
				},
				.
				.
				.
			]
		end note

	note over mil_registry #Orange
		On any failure, return HTTP 500 (server error) with specific error body. 
	end note
end