group get terminal data
	mil_auth -> mil_auth : POST /token
		note left #LightGreen
			__request body__
			client_id=//<mil-auth client id>//&
			grant_type=client_credentials&
			client_secret=//<secret>//
			__response body__
			{
				"access_token": "//<mil-auth ccess token>//",
				"token_type": "Bearer",
				"expires_in": //<access token duration>//
			}
			__//<mil-auth access token>//__
			base64url(//<token header>//) + "." +
			base64url(//<access token payload>//) + "." +
			//<base64url of access token signature>//
			__//<access token payload>//__
			{
				"sub": "//<mil-auth client id>//",
				"aud": "mil.pagopa.it",
				"iss": "https:////<host name>///mil-auth",
				"iat": //<issue unix epoch>//,
				"exp": //<expiration unix epoch>//,
				"groups": [
					.
					.
					.
					"pos_finder",
					.
					.
					.
				],
			}
		end note

	mil_auth -> mil_registry ++ : GET /poses?gtId=//<gt id>//&terminalId=//<terminal id>//
		note left
			__header__
			RequestId: //<request id>//
			Authorization: Bearer //<mil-auth access token>//
		end note
	
	mil_registry -> registry ++ : stream(//query document//)
		note left
			__//query document//__
			{
				"gtId": "//<gt id>//",
				"terminalId": "//<terminal id>//"
			}
		end note

	registry --> mil_registry -- : //document//
		note right
			__//document//__
			{
				"uuid": "//<terminal uuid>//",
				"manId": "//<client id of the subject who registered the POS>//",
				"gtId": "//<gt id>//",
				"terminalId": "//<terminal id>//",
				"enabled": //<enabled>//,
				"payeeCode": "//<payee code>//",
				"slave": "//<slave>//",
				"workstations": [
					.
					.
					.
					//<workstation #n>//,
					.
					.
					.
				],
				"pagoPa": "//<pagopa>//",
				"pspId": "//<psp id>//",
				"brokerId": "//<broker id>//",
				"channelId": "//<channel id>//",
				"idpay": "//<idpay>//"
			}
		end note
	
	mil_registry --> mil_auth -- : HTTP 200 (ok)
		note right
			__body__
			//See document//
		end note
	
	note over mil_registry #Orange
		On terminal not found, return HTTP 404 (not found).
		On any other failure, return HTTP 500 (server error) with specific error body. 
	end note
	
	note over mil_auth #Orange
		On terminal not found, return HTTP 401 (unauthorized) with specific error body.
		On //<enabled>// = false, return HTTP 401 (unauthorized) with specific error body.
		On any other failure, return HTTP 500 (server error) with specific error body. 
    end note
end