group #E6E6FA get number of terminals
	mil -> registry ++ :  count(//query document//)
		note left
			__//query document//__
			{
				"manId": "//<client id>//",
				"payeeCode": "//<payee code>//"
			}
		end note

	registry --> mil -- : //<number of elements>//

	note over mil #Orange
		On any failure, return HTTP 500 (server error) with specific error body. 
	end note
end