group get terminals data
	mil_registry -> registry ++ : find(//query document//).page(//<page number>//, //<page size>//)
		note left
			__//query document//__
			{
				"manId": "//<client id>//"
			}
		end note

	registry --> mil_registry -- : //page//
		note right
			__//page//__
			[
				{
					"uuid": "//<terminal uuid>//",
					"manId": "//<client id of the subject who registered the POS>//",
					"gtId": "//<gt id>//",
					"terminalId": "//<terminal id>//",
					"enabled": //<enabled>//,
					"payeeCode": "//<payee code>//",
					"slave": "//<slave>//",
					"workstations": [
						.
						.
						.
						//<workstation #n>//,
						.
						.
						.
					],
					"pagoPa": "//<pagopa>//",
					"pspId": "//<psp id>//",
					"brokerId": "//<broker id>//",
					"channelId": "//<channel id>//",
					"idpay": "//<idpay>//"
				},
				.
				.
				.
			]
		end note

	note over mil_registry #Orange
		On any failure, return HTTP 500 (server error) with specific error body. 
	end note
end