@startuml
!include_many skin.puml
!include_many actors.puml

activate pos

pos -> mil ++ : POST /token
	note left
		__header__
		RequestId: //<request id>//
		__body__
		grant_type=device_code
		&&client_id=//<client id>//
		&&device_code=//<terminal uuid>//
	end note

!include_many get_auth_state.puml
!include_many build_tokens.puml

mil --> pos -- : HTTP 200 (ok)
	note right
		{
    		"access_token": "//<access token>//",
    		"refresh_token": "//<refresh token>//",
    		"token_type": "Bearer",
    		"expires_in": 900 <&arrow-left> //This must be a conf. par.//
		}
	end note

deactivate pos
@enduml