@startuml
!include_many skin.puml
!include_many actors.puml

activate pos

pos -> mil ++ : POST /token
	note left
		__header__
		RequestId: //<request id>//
		__body__
		grant_type=device_code
		&&client_id=//<client id>//
		&&device_code=//<terminal uuid>//
	end note

!include_many get_auth_state.puml
!include_many verify_client_id.puml
!include_many get_terminal_data.puml
!include_many build_tokens_payload.puml
!include_many retrieve_key_to_sign_tokens.puml
!include_many build_tokens_header.puml
!include_many sign_access_token.puml

mil -> mil : //<access token>// = base64url(//<token header>//) + "." +  base64url(//<access token payload>//) + "." + //<base64url of access token signature>//

!include_many sign_refresh_token.puml

mil -> mil : //<refresh token>// = base64url(//<token header>//) + "." +  base64url(//<refresh token payload>//) + "." + //<base64url of refresh token signature>//

mil --> pos -- : HTTP 200 (ok)
	note right
		{
    		"access_token": "//<access token>//",
    		"refresh_token": "//<refresh token>//",
    		"token_type": "Bearer",
    		"expires_in": 900 <&arrow-left> //This must be a conf. par.//
		}
	end note

deactivate pos
@enduml