@startuml
!include_many skin.puml
!include_many actors.puml

activate installer

installer -> management ++ : authorize device (in: //<user code>//)
management -> mil ++ : POST /activate
	note left
		__header__
		RequestId: //<request id>//
		Authorization: Bearer //<access token>//
		__body__
		user_code=//<user code>//
	end note

!include_many get_user_code.puml
!include_many store_auth_state.puml

mil --> management -- : ok
management --> installer -- : ok

deactivate installer
@enduml