@startuml
!include_many skin.puml
!include_many actors.puml

activate operator

operator -> management ++ : register POS

management -> mil ++ : POST /poses
	note left
		__header__
		RequestId: //<request id>//
		Authorization: Bearer //<access token>//
		__body__
		{
			"gtId": "//<gt id>//",
			"terminalId": "//<terminal id>//",
			"payeeCode": "//<payee code>//", <&arrow-left> //Payee's Tax (Fiscal) Code for PA POS, Mechant's Tax (Fiscal) Code for other POS.//
			"slave": "//<slave>//", <&arrow-left> //True for slave PA POS, otherwise false.//
			"pagoPa": "//<pagopa>//", <&arrow-left> //True for POS enbled to pagoPA payments.//
			"pspId": "//<psp id>//", <&arrow-left> //Present if <pagopa> is true. PSP ID to use to communicate with pagoPA platform.//
			"brokerId": "//<broker id>//", <&arrow-left> //Present if <pagopa> is true. PSP Broker ID to use to communicate with pagoPA platform.//
			"channelId": "//<channel id>//", <&arrow-left> //Present if <pagopa> is true. Channel ID to use to communicate with pagoPA platform.//
			"idpay": "//<idpay>//" <&arrow-left> //True for POS enabled to use IDPay bonus.//
		}
	end note

mil -> mil : generate //<terminal uuid>//

!include_many store_terminal_data.puml

mil --> management -- : HTTP 201 (created)
	note right
		__header__
		Location: /poses///<terminal uuid>//
	end note

management --> operator -- : ok

deactivate operator
@enduml