@startuml
!include_many skin.puml
!include_many actors.puml

activate operator

operator -> management ++ : register POS

management -> mil_registry ++ : POST /terminals
	note left
		__header__
		RequestId: //<request id>//
		Authorization: Bearer //<access token>//
		__body__
		{
			"terminalHandlerId": "//<terminal handler id>//",
			"terminalId": "//<terminal id>//",
			"enabled": //<enabled>//,
			"payeeCode": "//<payee code>//",
			"slave": "//<slave>//",
			"pagoPa": "//<pagopa>//",
			"pagoPaConf": {
				"pspId": "//<psp id>//",
				"brokerId": "//<broker id>//",
				"channelId": "//<channel id>//"
			},
			"idpay": "//<idpay>//"
		}
	end note

note over mil_registry #LightGreen
	__//<access token>//__
	base64url(//<token header>//) + "." +
	base64url(//<access token payload>//) + "." +
	//<base64url of access token signature>//
	__//<access token payload>//__
	{
		"sub": "//<service provider id>//",
		"aud": "mil.pagopa.it",
		"iss": "https:////<host name>///mil-auth",
		"iat": //<issue unix epoch>//,
		"exp": //<expiration unix epoch>//,
		"groups": [
			"pos_service_provider"
		]
	}
end note

mil_registry -> mil_registry : generate //<terminal uuid>//
	note left
		new SecureRandom().ints(0, 16)
			.limit(24)
			.mapToObj(Integer::toHexString)
			.collect(Collectors.joining());
	end note

!include_many store_terminal_data.puml

mil_registry --> management -- : HTTP 201 (created)
	note right
		__header__
		Location: /terminals///<terminal uuid>//
	end note

management --> operator -- : ok

deactivate operator
@enduml