@startuml
!include_many skin.puml
!include_many actors.puml

activate operator

operator -> management ++ : update POS

management -> mil_registry ++ : PATCH /terminals///<terminal uuid>//
	note left
		__header__
		RequestId: //<request id>//
		Authorization: Bearer //<access token>//
		__body__
		{
			"gtId": "//<new gt id>//",
			"terminalId": "//<new terminal id>//",
			"enabled": //<new enabled>//,
			"payeeCode": "//<new payee code>//",
			"slave": "//<new slave>//",
			"pagoPa": "//<new pagopa>//",
			"pagoPaConf": {
				"pspId": "//<new psp id>//",
				"brokerId": "//<new broker id>//",
				"channelId": "//<new channel id>//"
			},
			"idpay": "//<new idpay>//"
		}
	end note

note over mil_registry #LightGreen
	__//<access token>//__
	base64url(//<token header>//) + "." +
	base64url(//<access token payload>//) + "." +
	//<base64url of access token signature>//
	__//<access token payload>//__
	{
		"sub": "//<service provider id>//",
		"aud": "mil.pagopa.it",
		"iss": "https:////<host name>///mil-auth",
		"iat": //<issue unix epoch>//,
		"exp": //<expiration unix epoch>//,
		"groups": [
			"pos_service_provider",
		]
	}
end note

!include_many get_terminal_data_by_id_for_psp.puml

mil_registry -> mil_registry : update retrieved document with new values

!include_many update_terminal_data_for_psp.puml

mil_registry --> management -- : HTTP 204 (no content)

management --> operator -- : ok

deactivate operator
@enduml