@startuml
!include_many skin.puml
!include_many actors.puml

activate operator

operator -> management ++ : get POS list

management -> mil_registry ++ : GET /terminals?page=//<page number>//&size=//<page size>//
	note left
		__header__
		RequestId: //<request id>//
		Authorization: Bearer //<access token>//
	end note

note over mil_registry #LightGreen
	__//<access token>//__
	base64url(//<token header>//) + "." +
	base64url(//<access token payload>//) + "." +
	//<base64url of access token signature>//
	__//<access token payload>//__
	{
		"sub": "//<service provider id>//",
		"aud": "mil.pagopa.it",
		"iss": "https:////<host name>///mil-auth",
		"iat": //<issue unix epoch>//,
		"exp": //<expiration unix epoch>//,
		"groups": [
			"pos_service_provider"
		]
	}
end note

!include_many get_number_of_terminals_for_psp.puml
!include_many get_terminals_data_for_psp.puml

mil_registry -> mil_registry : //<number of pages>// = ceil( //<number of elements>// / //<page size>// )

mil_registry --> management -- : HTTP 200 (ok)
	note right
		__body__
		{
			"terminals": [
				{
					"terminalUuid": "//<terminal uuid>//",
					"serviceProviderId": "//<service provider id>//",
					"terminalHandlerId": "//<terminal handler id>//",
					"terminalId": "//<terminal id>//",
					"enabled": //<enabled>//,
					"payeeCode": "//<payee code>//",
					"slave": "//<slave>//",
					"workstations": [
						//<array of workstations>//
					],
					"pagoPa": "//<pagopa>//",
					"pagoPaConf": {
						"pspId": "//<psp id>//",
						"brokerId": "//<broker id>//",
						"channelId": "//<channel id>//"
					},
					"idpay": "//<idpay>//"
				},
                .
                .
                .
			],
			"page": {
				"size": //<page size>//,
				"totalElements": //<number of elements>//,
				"totalPages": //<number of pages>//
			}
		}
	end note

management --> operator -- : POS list

deactivate operator
@enduml