@startuml
!include_many skin.puml
!include_many actors.puml

activate pos

pos -> mil_auth ++ : POST /token
	note left
		__header__
		RequestId: //<request id>//
		__body__
		grant_type=refresh_token&
		client_id=//<client id>//&
		refresh_token=//<<refresh token>//
	end note

!include_many verify_refresh_token.puml
!include_many build_tokens.puml

mil_auth --> pos -- : HTTP 200 (ok)
	note right
		{
    		"access_token": "//<access token>//",
    		"refresh_token": "//<refresh token>//",
    		"token_type": "Bearer",
    		"expires_in": 900 <&arrow-left> //This must be a conf. par.//
		}
	end note

deactivate pos
@enduml