group #80FFDB retrieve key to sign tokens
	!include_many get_valid_keys.puml
	
	alt there are no valid key
		!include_many create_new_key.puml
	else there are valid keys
		mil -> mil : search the key with greatest expiration
	end

    note over mil #LightGreen
		Here the //key// to use to sign the tokens.
		__//key//__
		{
			"kid": "//<key name>/////<key version>//",
			"iat": //<issued at>//,
			"exp": //<expiration>//,
			"use": "sig",
			"kty": "RSA",
			"n": "//<modulus>//",
			"e": "//<public exponent>//"
		}
    end note
end