group #DCCCFF sign refresh token
	mil -> mil : generate //<string to sign for refresh token>//
		note left
			__//<string to sign for refresh token>//__
			base64url(
				sha256(
					utf8(
						base64url(//<token header>//) +
						"." +
						base64url(//<refresh token payload>//)
					)
				)
			)
		end note

	mil -> azure_kv ++ : POST POST //<key vault base url>///keys///<key name>/////<key version>///sign?api-version=7.4
		note left
			__header__
			Authorization: Bearer //<access token for key vault>//
			__body__
			{
				"alg": "RS256",
				"value": "//<string to sign for refresh token>//"
			}
		end note

	azure_kv --> mil -- : HTTP 200 (ok)
		note right
			__body__
			{
				"kid": "//<key vault base url>///keys///<key name>/////<key version>//",
				"value": "//<base64url of refresh token signature>//"
			}
		end note

	note over mil #Orange
		On any failure, return HTTP 500 (server error) with specific error body. 
	end note
end