group set auth state
    mil_auth -> cache ++ : put(//<terminal uuid>//, true) with expiration time equals to //<expires is>//
    cache --> mil_auth -- : ok

    note over mil_auth #Orange
	    On any failure, return HTTP 500 (server error) with specific error body. 
    end note
end