group store terminal data
	mil_registry -> registry ++ : persist(//document//)
		note left
			__//document//__
			{
				"terminalUuid": "//<terminal uuid>//",
				"serviceProviderId": "//<service provider id>//",
				"terminalHandlerId": "//<terminal handler id>//",
				"terminalId": "//<terminal id>//",
				"enabled": //<enabled>//,
				"payeeCode": "//<payee code>//",
				"slave": "//<slave>//",
				"pagoPa": "//<pagopa>//",
				"pagoPaConf": {
					"pspId": "//<psp id>//",
					"brokerId": "//<broker id>//",
					"channelId": "//<channel id>//"
				},
				"idpay": "//<idpay>//"
			}
		end note

	registry --> mil_registry -- : ok

    note over mil_registry #Orange
		On duplicate key (//<terminal handler id>//, //<terminal id>//) error is returned, return HTTP 409 (conflict).
		On any other failure, return HTTP 500 (server error) with specific error body. 
	end note
end