group #FFCCAA store user code
	mil -> cache ++ : put(//<user code>//, //<terminal uuid>//) with expiration time equals to //<expires is>//
	cache --> mil -- : ok

    note over mil #Orange
	    On any failure, return HTTP 500 (server error) with specific error body. 
    end note
end